export const projects = [
    {
        image: "/image/minecraft_tetris.png",
        title: "Minecraft Tetris",
        subtitle: "Using HTML, CSS, and JavaScript",
        handle: "by apurvakumar17",
        borderColor: "#3B82F6",
        gradient: "linear-gradient(145deg, #3B82F6, #000)",
        url: "https://github.com/sarahjohnson",
    },
    {
        image: "/image/tictactoe.png",
        title: "TicTacToe",
        subtitle: "Using JAVA",
        handle: "by apurvakumar17",
        borderColor: "#10B981",
        gradient: "linear-gradient(180deg, #10B981, #000)",
        url: "https://linkedin.com/in/mikechen",
    },
    {
        image: "/image/snake_game.png",
        title: "Snake Game",
        subtitle: "Using HTML, CSS, and JavaScript",
        handle: "by apurvakumar17",
        borderColor: "#F59E0B",
        gradient: "linear-gradient(210deg, #F59E0B, #000)",
        url: "https://dribbble.com/emilydavis",
    },
    {
        image: "/image/matrix_magic.png",
        title: "Matrix Magic",
        subtitle: "Using HTML, CSS, and JavaScript",
        handle: "by apurvakumar17",
        borderColor: "#EF4444",
        gradient: "linear-gradient(195deg, #EF4444, #000)",
        url: "https://kaggle.com/davidsmith",
    },
    {
        image: "/image/3in1.png",
        title: "3 in 1 Project",
        subtitle: "Using HTML, CSS, and JavaScript",
        handle: "by apurvakumar17",
        borderColor: "#8B5CF6",
        gradient: "linear-gradient(160deg, #8B5CF6, #000)",
        url: "https://behance.net/lindapark",
    },
    {
        image: "/image/music_player.png",
        title: "Music Player",
        subtitle: "Using HTML, CSS, and JavaScript",
        handle: "by apurvakumar17",
        borderColor: "#EC4899",
        gradient: "linear-gradient(175deg, #EC4899, #000)",
        url: "https://github.com/jasonlee",
    },
];
