export const skillsData = [
    "HTML",
    "CSS",
    "Javascript",
    "React",
    "MySQL",
    "C",
    "JAVA",
    "Python",
    "Photoshop",
    "Illustrator",
    "Lightroom",
    "Microsoft Office",
    "PowerBI",
    "Git",
    "Bootstrap",
    "Tailwind",
    "Figma",
    "MaterialUI",
];
